name: windows1251
version: 2.0.1
description: Cyrillic windows-1251 (cp1251) encoding implementation for Dart.
repository: https://github.com/ykmnkmi/windows1251.dart

topics:
  - cyrrylic
  - windows-1251
  - cp1251
  - encode
  - decode

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
